### ISSUE TITLE
Tests d'interfaces (E2E/fonctionnels) sur la plateforme

### ISSUE THREAD

**Issue by Renaud009** [Ouranosinc/PAVICS-e2e-ui-tests#1]
Couverture minimale des fonctionnalités de la plateforme pour l'instant.
Évaluer la pertinence d'avoir un repo indépendant (et image docker)

**Comment by Renaud009** [comment]
@ldperron Integrate pavics/pavics-e2e-ui-tests in jenkins that should be ran on hirondelle after every deployment

**Comment by ldperron** [comment]
Integration with Jenkins done.
After a deployment on hirondelle, the test will be automatically triggered within 5 minutes.

**Comment by Renaud009** [comment]
Deployed on hirondelle as a jenkin task
